export const endPoint = {
   accountStatus: 'AccountStatus/GetMovements',
   accountStatusCreate: 'AccountStatus/Create',
   balance: 'Balance',
   confirmRecoverPassword: 'Password/ConfirmRecover',
   contactsCreate: 'Contacts/Create',
   contactsEdit: 'Contacts/Edit',
   contactsDelete: 'Contacts/Delete',
   contactsGetAll: 'Contacts/Get',
   corporateCardsGetAll: 'CorporateCards/GetAll',
   corporateCardsAsignCard: 'CorporateCards/AssignCard',
   corporateCardsLockSubaccountCards: 'CorporateCards/LockSubaccountCard',
   corporateCardsUnlockSubaccountCards: 'CorporateCards/UnlockSubAccountCard',
   dataSpei: 'DataSpei',
   getBanks: 'Banks/Get',
   getContacts: 'Contacts/Get',
   getDispersion: 'Dispersion/Get',
   getDispersionDetail: 'DetailDispersion/GetDetail',
   getName: 'GetNameToLogin',
   getUserInfo: 'UsersMorales/GetUser',
   historyMovementsDownloadFiles: 'HistoryMovements/DownloadFiles',
   login: 'Login',
   loginTwoFactor: 'LoginTwoFactor',
   movements: 'HistoryMovements/Get',
   private: 1,
   public: 0,
   recoverPassword: 'Password/Recover',
   requestCorporateCards: 'RequestCorporateCards',
   servicePay: 'ServicePay',
   services: 'Services/Get',
   setSessionActivity: 'SetSessionActivity',
   token: 'Token',
   twoFactorDisable: 'TwoFactor/Disable',
   twoFactorEnabled: 'TwoFactor/Enable',
   twoFactorLoadCodes: 'TwoFactor/LoadCodes',
   uploadDocument: 'UploadDocument',
   banksGetTemplate: 'Banks/GetTemplate',
   GetDetailDispersionDownload: 'DetailDispersion/Download',
   dispersionCreate: 'Dispersion/Create',
   dispersionTemplatesDownloadSpei: 'DispersionTemplatesDownload/Spei',
   dispersionTemplatesDownloadCorporateCards:
      'DispersionTemplatesDownload/CorporateCards',
   getdetailDispersion: 'DetailDispersion/GetDetail',
   setDispersionesEncoladas: 'DispersionesEncoladas',
   setDispersionReject: 'Dispersion/Reject',
   dispersionGetAuthorizersAndNotifiers:
      'Dispersion/GetAuthorizersAndNotifiers',
   dispersionConfirmCreation: 'Dispersion/ConfirmCreation',
   dispersionCancel: 'Dispersion/Cancel',
   detailDispersionOtp: 'DetailDispersion/Otp',
   dispersionRequestAuthorization: 'Dispersion/RequestAuthorization',
   setAddBalance: 'CorporateCards/AddBalance',
   setDecreaseBalance: 'CorporateCards/DecreaseBalance',
   setNewCard: 'CorporateCards/ReplaceCard',
   sendMoney: 'SendMoney/Process',
   getTicket: 'Ticket',
   contactsGetAllNoPagination: 'Contacts/GetAllContacts',
   sendMoneyGetAuthorizersAndNotifiers:'SendMoney/GetAuthorizersAndNotifiers',
   sendMoneyConfirm:'SendMoney/Confirm',
   sendMoneyReject:'SendMoney/Reject',
   sendMoneyUploadDepositReceipt:'SendMoney/UploadDepositReceipt',
   bitrusOperation:'Bitrus/Operation',
   bitrusGenerateOtp:'Bitrus/GenerateOtp',
   termsAndConditions:'TermsAndConditions/AcceptTerms',
   getCatalog:'Catalog/Get'
};
